### ISSUE TITLE
03 -scoreboard - using javascript

### ISSUE THREAD

**Issue by gevers3** [gevers3/assignments#4]
# Score Board

For this assignment, you will be creating a simple interactive scoreboard for your favorite sport.

## Requirements

- Refer to this mockup to design your page:

![](https://github.com/suncoast-devs/handbook/blob/a2f0c05d3914a8f16611da03a18dbe92cd821a92/curriculum/fundamentals/modules/javascript/_old/assignments/assets/scoreboard.png?raw=true)

- Use the HTML and CSS [here](https://gist.github.com/mdewey/d331c0a449b8e53b4adc472ec0e5a1e8) to jump-start your project.
- A user should be able to update a score and the teams playing.

### Explorer Mode

- [x] Create a new project and implement the design using the given HTML & CSS.
- [x] Assign click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard-coded" value.
- [x] Deploy your site.

### Adventure Mode

- [x] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [x] Add some styling to make it more presentable. Have fun with it.
- [x] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add CSS to the winning teams score to indicate who is currently winning.
- [ ] Add anything else that your sport would have on its scoreboard (e.g. fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

**Comment by gevers3** [comment]
https://github.com/gevers3/scoreboard-2.git

**Comment by gevers3** [comment]
https://github.com/gevers3/scoreboard-2

**Comment by gevers3** [comment]
My previous comment only included the link to github - it is now updated here with a link to the deployed netlify site:
https://scoreboard-2-gevers3.netlify.com/

**Comment by lizthrilla** [comment]
Gorgeous as usual with a nice responsive layout.  Just needs to have the ability to edit the team names, but very good.

**Comment by gevers3** [comment]
Your homework **03 -scoreboard - using javascript** was marked: **Exceeds Expectations**

![Niiiiiiiiice!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f7e0d5535291cc82f410da4761392ed248ba5a6/tumblr_inline_odd2x9PvYg1raprkq_400.gif)
> &ldquo;Niiiiiiiiice!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/65)**__
